title: Rui Ding
author: Rui Ding
description: > # this means to ignore newlines until "show_exerpts:"
  Rui Ding received the B.S degree in Communication Engineering from NUIST, Jiangsu, China, in 2020. He received his M. S. E degree in Information and Communication Engineering in 2023. 04 in NUAA. He is currently working towards the Ph.D. degree in NUAA, Jiangsu, China, supervised by Prof. Fuhui Zhou and Prof. Qihui Wu. His current research interests include intelligent spectrum cognitive and spectrum decision, resource optimization.
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/minasrc  
      icon: twitter-square
      color: cyan
    - url: https://github.com/minasrc
      icon: github-square
      color: cyan

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: local
  avatar_path: /assets/avatar.jpg

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
