title: minasrc
author: minasrc
description: > # this means to ignore newlines until "show_exerpts:"
  A small corner on the internet for my braindump. I am a computer science student interested in cybersecurity and currently working as a software developer. I write about tech, books, life, the thoughts that keep you up at night.. basically everything.
show_excerpts: true # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/minasrc  
      icon: twitter-square
      color: cyan
    - url: https://github.com/minasrc
      icon: github-square
      color: cyan

  # wether the author box should be displayed
  show_author: true

  # the animation speed of the scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: local
  avatar_path: /assets/avatar.jpg

# Build settings

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
